//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.2523.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Web.Services.Protocols;
using System.Web.Services;


[System.Web.Services.WebServiceBindingAttribute(Name="BugListServiceSoap", Namespace="http://tempuri.org/")]
public class BugListService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    public BugListService() {
        this.Url = "http://ericz03/bugsweb/services/bugsservice.asmx";
    }
    
    [System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/GetBugList", MessageStyle=System.Web.Services.Protocols.SoapMessageStyle.ParametersInDocument)]
    public BugsWebServiceError GetBugList(string databaseName, string sql, out System.Data.DataSet data) {

        object[] results = this.Invoke("GetBugList", new object[] {databaseName,
                    sql});
        data = ((System.Data.DataSet)(results[1]));
        return ((BugsWebServiceError)(results[0]));
    }
    
    public System.IAsyncResult BeginGetBugList(string databaseName, string sql, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetBugList", new object[] {databaseName,
                    sql}, callback, asyncState);
    }
    
    public BugsWebServiceError EndGetBugList(System.IAsyncResult asyncResult, out System.Data.DataSet data) {
        object[] results = this.EndInvoke(asyncResult);
        data = ((System.Data.DataSet)(results[1]));
        return ((BugsWebServiceError)(results[0]));
    }
}

public class BugsWebServiceError {
    
    public string Message;
    
    public string ExceptionName;
    
    public bool HasError;
}
