'Copyright (C) 2003 Microsoft Corporation
'All rights reserved.
'
'THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER
'EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
'MERCHANTIBILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
'
'Date: February, 2003
'Author: Duncan Mackenzie
'http://www.gotdotnet.com/Community/User/viewprofile.aspx?userid=00011A674C38C375  
'Requires the release version of .NET Framework 
Imports System
Imports System.Windows.Forms
Imports System.IO
Imports System.Text.RegularExpressions

Public Class addNewJob
    Inherits System.Windows.Forms.Form

    'settings are stored here
    Dim m_Options As Options

    Public Property Options() As Options
        'pass user settings in from calling form
        Get
            Return m_Options
        End Get
        Set(ByVal Value As Options)
            m_Options = Value
        End Set
    End Property
    Public Property Target() As String
        'save file to where?
        Get
            Return Me.Destination.Text
        End Get
        Set(ByVal Value As String)
            Me.Destination.Text = Value
        End Set
    End Property
    Public Property SourceURL() As String
        'what file to go get?
        Get
            Return Me.Source.Text
        End Get
        Set(ByVal Value As String)
            Me.Source.Text = Value
        End Set
    End Property

#Region " Windows Form Designer generated code "

    Public Sub New()
        MyBase.New()

        'This call is required by the Windows Form Designer.
        InitializeComponent()

        'Add any initialization after the InitializeComponent() call

    End Sub

    'Form overrides dispose to clean up the component list.
    Protected Overloads Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing Then
            If Not (components Is Nothing) Then
                components.Dispose()
            End If
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    Friend WithEvents sourceInfo As System.Windows.Forms.GroupBox
    Friend WithEvents Source As System.Windows.Forms.TextBox
    Friend WithEvents destInfo As System.Windows.Forms.GroupBox
    Friend WithEvents Destination As System.Windows.Forms.TextBox
    Friend WithEvents OkBtn As System.Windows.Forms.Button
    Friend WithEvents CancelBtn As System.Windows.Forms.Button
    Friend WithEvents browseForFile As System.Windows.Forms.Button
    Friend WithEvents saveDestinationAs As System.Windows.Forms.SaveFileDialog
    Friend WithEvents autoGenerateDestination As System.Windows.Forms.CheckBox
    <System.Diagnostics.DebuggerStepThrough()> Private Sub InitializeComponent()
        Dim resources As System.Resources.ResourceManager = New System.Resources.ResourceManager(GetType(addNewJob))
        Me.sourceInfo = New System.Windows.Forms.GroupBox()
        Me.Source = New System.Windows.Forms.TextBox()
        Me.destInfo = New System.Windows.Forms.GroupBox()
        Me.Destination = New System.Windows.Forms.TextBox()
        Me.OkBtn = New System.Windows.Forms.Button()
        Me.CancelBtn = New System.Windows.Forms.Button()
        Me.browseForFile = New System.Windows.Forms.Button()
        Me.saveDestinationAs = New System.Windows.Forms.SaveFileDialog()
        Me.autoGenerateDestination = New System.Windows.Forms.CheckBox()
        Me.sourceInfo.SuspendLayout()
        Me.destInfo.SuspendLayout()
        Me.SuspendLayout()
        '
        'sourceInfo
        '
        Me.sourceInfo.Controls.AddRange(New System.Windows.Forms.Control() {Me.Source})
        Me.sourceInfo.Location = New System.Drawing.Point(8, 8)
        Me.sourceInfo.Name = "sourceInfo"
        Me.sourceInfo.Size = New System.Drawing.Size(328, 48)
        Me.sourceInfo.TabIndex = 0
        Me.sourceInfo.TabStop = False
        Me.sourceInfo.Text = "Source (URL)"
        '
        'Source
        '
        Me.Source.Location = New System.Drawing.Point(8, 16)
        Me.Source.Name = "Source"
        Me.Source.Size = New System.Drawing.Size(312, 20)
        Me.Source.TabIndex = 0
        Me.Source.Text = "Source"
        '
        'destInfo
        '
        Me.destInfo.Controls.AddRange(New System.Windows.Forms.Control() {Me.browseForFile, Me.Destination, Me.autoGenerateDestination})
        Me.destInfo.Location = New System.Drawing.Point(8, 64)
        Me.destInfo.Name = "destInfo"
        Me.destInfo.Size = New System.Drawing.Size(328, 64)
        Me.destInfo.TabIndex = 1
        Me.destInfo.TabStop = False
        Me.destInfo.Text = "Destination (File)"
        '
        'Destination
        '
        Me.Destination.Location = New System.Drawing.Point(8, 16)
        Me.Destination.Name = "Destination"
        Me.Destination.ReadOnly = True
        Me.Destination.Size = New System.Drawing.Size(280, 20)
        Me.Destination.TabIndex = 0
        Me.Destination.Text = "Destination"
        '
        'OkBtn
        '
        Me.OkBtn.DialogResult = System.Windows.Forms.DialogResult.OK
        Me.OkBtn.Location = New System.Drawing.Point(216, 136)
        Me.OkBtn.Name = "OkBtn"
        Me.OkBtn.Size = New System.Drawing.Size(56, 23)
        Me.OkBtn.TabIndex = 2
        Me.OkBtn.Text = "OK"
        '
        'CancelBtn
        '
        Me.CancelBtn.DialogResult = System.Windows.Forms.DialogResult.Cancel
        Me.CancelBtn.Location = New System.Drawing.Point(280, 136)
        Me.CancelBtn.Name = "CancelBtn"
        Me.CancelBtn.Size = New System.Drawing.Size(56, 23)
        Me.CancelBtn.TabIndex = 3
        Me.CancelBtn.Text = "Cancel"
        '
        'browseForFile
        '
        Me.browseForFile.Enabled = False
        Me.browseForFile.Location = New System.Drawing.Point(296, 16)
        Me.browseForFile.Name = "browseForFile"
        Me.browseForFile.Size = New System.Drawing.Size(24, 20)
        Me.browseForFile.TabIndex = 1
        Me.browseForFile.Text = "..."
        '
        'saveDestinationAs
        '
        Me.saveDestinationAs.FileName = "doc1"
        Me.saveDestinationAs.RestoreDirectory = True
        Me.saveDestinationAs.Title = "Save Download As"
        '
        'autoGenerateDestination
        '
        Me.autoGenerateDestination.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.autoGenerateDestination.Location = New System.Drawing.Point(24, 40)
        Me.autoGenerateDestination.Name = "autoGenerateDestination"
        Me.autoGenerateDestination.Size = New System.Drawing.Size(168, 16)
        Me.autoGenerateDestination.TabIndex = 2
        Me.autoGenerateDestination.Text = "Auto-Generate Destination"
        '
        'addNewJob
        '
        Me.AutoScaleBaseSize = New System.Drawing.Size(5, 13)
        Me.ClientSize = New System.Drawing.Size(344, 168)
        Me.Controls.AddRange(New System.Windows.Forms.Control() {Me.CancelBtn, Me.OkBtn, Me.sourceInfo, Me.destInfo})
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.MaximizeBox = False
        Me.MinimizeBox = False
        Me.MinimumSize = New System.Drawing.Size(352, 0)
        Me.Name = "addNewJob"
        Me.Text = "Create New Background Copy Job"
        Me.sourceInfo.ResumeLayout(False)
        Me.destInfo.ResumeLayout(False)
        Me.ResumeLayout(False)

    End Sub

#End Region

    Private Sub browseForFile_Click( _
            ByVal sender As System.Object, _
            ByVal e As System.EventArgs) _
        Handles browseForFile.Click

        'Pull filename out of Source URL
        Dim fileName As String
        If ValidURL(Me.Source.Text) Then
            Dim source As New Uri(Me.Source.Text)
            'get file name
            fileName = Path.GetFileName(source.LocalPath)
        Else
            fileName = ""
        End If

        'saveDestinationAs is a SaveFileDialog control on Form
        Me.saveDestinationAs.FileName = fileName
        If Not m_Options Is Nothing Then
            Me.saveDestinationAs.InitialDirectory = _
                m_Options.defaultSaveLocation
        End If

        If Me.saveDestinationAs.ShowDialog() _
                = DialogResult.OK Then
            Me.Destination.Text = saveDestinationAs.FileName
        End If
    End Sub

    Private Function AutoGenerateTarget(ByVal sourceURL As String) As String
        'come up with a local destination based on the remote path
        Try
            Dim fileName As String
            'Get Target
            Dim source As New Uri(sourceURL.Trim)

            'Get file name
            fileName = Path.GetFileName(source.LocalPath)
            Return _
                Path.Combine(m_Options.defaultSaveLocation, fileName)
        Catch ex As Exception
            MsgBox(ex.ToString)
            Return ""
        End Try
    End Function

    Private Function ValidURL( _
        ByVal sourceURL As String) As Boolean
        'Check if a valid URL has been entered
        Dim urlValidator As String = _
        "http:\/\/[\w]+(.[\w]+)([\w\-\.," & _
            "@?^=%&:/~\+#]*[\w\-\@?^=%&/~\+#])?"
        Dim r As New Regex( _
            urlValidator)
        Return r.IsMatch(sourceURL.Trim)
    End Function

    Private Sub Source_Leave(ByVal sender As Object, ByVal e As System.EventArgs) Handles Source.Leave
        'just check if we are supposed to auto generate the local path
        If Me.autoGenerateDestination.Checked AndAlso ValidURL(Me.Source.Text) Then
            Me.Destination.Text = AutoGenerateTarget(Me.Source.Text)
        End If
    End Sub

    Private Sub autoGenerateDestination_CheckedChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles autoGenerateDestination.CheckedChanged
        'change UI cues if check box state is changed
        If autoGenerateDestination.Checked Then
            Me.Destination.ReadOnly = True
            Me.browseForFile.Enabled = False
            If ValidURL(Me.Source.Text) Then
                Me.Destination.Text = _
                    AutoGenerateTarget(Me.Source.Text)
            End If
        Else
            Me.Destination.ReadOnly = False
            Me.browseForFile.Enabled = True
        End If
    End Sub
End Class

