//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace DavesQuickSearchDeskbar {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class search {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("copyright", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("comment", typeof(searchComment))]
        [System.Xml.Serialization.XmlElementAttribute("created_by", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("version", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("email", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("link", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("description", typeof(searchDescription))]
        [System.Xml.Serialization.XmlElementAttribute("COMMENT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("todo", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("script", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("form", typeof(searchForm))]
        [System.Xml.Serialization.XmlElementAttribute("contributor", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("category", typeof(searchCategory))]
        [System.Xml.Serialization.XmlElementAttribute("idea", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string function;
    }
    
    /// <remarks/>
    public class searchComment {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("table", typeof(searchCommentTable))]
        [System.Xml.Serialization.XmlElementAttribute("div", typeof(searchCommentDiv))]
        public object[] Items;
    }
    
    /// <remarks/>
    public class searchCommentTable {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("td", typeof(string), IsNullable=false)]
        public string[][] tr;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class;
    }
    
    /// <remarks/>
    public class searchCommentDiv {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    public class searchFormINPUT {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NAME;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
    }
    
    /// <remarks/>
    public class searchFormInput {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VALUE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
    }
    
    /// <remarks/>
    public class searchFormCOMMENTSelectOption {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    public class searchFormCOMMENTSelect {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("option")]
        public searchFormCOMMENTSelectOption[] option;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    public class searchFormCOMMENT {
        
        /// <remarks/>
        public searchFormCOMMENTSelect select;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    public class searchForm {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comment", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("input", typeof(searchFormInput))]
        [System.Xml.Serialization.XmlElementAttribute("COMMENT", typeof(searchFormCOMMENT))]
        [System.Xml.Serialization.XmlElementAttribute("INPUT", typeof(searchFormINPUT))]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string method;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string METHOD;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ACTION;
    }
    
    /// <remarks/>
    public class searchDescriptionB {
        
        /// <remarks/>
        public string i;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    public class searchDescriptionA {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    public class searchDescriptionTableTRTDHR {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Byte size;
    }
    
    /// <remarks/>
    public class searchDescriptionTableTRTDTableTRTD {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("b")]
        public string[] b;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    public class searchDescriptionTableTRTDTable {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("td", typeof(searchDescriptionTableTRTDTableTRTD), IsNullable=false)]
        public searchDescriptionTableTRTDTableTRTD[][] tr;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class;
    }
    
    /// <remarks/>
    public class searchDescriptionTableTRTDA {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    public class searchDescriptionTableTRTDDiv {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("br")]
        public object[] br;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string style;
    }
    
    /// <remarks/>
    public class searchDescriptionTableTRTD {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("br", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("hr", typeof(searchDescriptionTableTRTDHR))]
        [System.Xml.Serialization.XmlElementAttribute("I", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("table", typeof(searchDescriptionTableTRTDTable))]
        [System.Xml.Serialization.XmlElementAttribute("nobr", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("b", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("i", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("div", typeof(searchDescriptionTableTRTDDiv))]
        [System.Xml.Serialization.XmlElementAttribute("a", typeof(searchDescriptionTableTRTDA))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Byte colspan;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool colspanSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nowrap;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string width;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        br,
        
        /// <remarks/>
        hr,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        table,
        
        /// <remarks/>
        nobr,
        
        /// <remarks/>
        b,
        
        /// <remarks/>
        i,
        
        /// <remarks/>
        div,
        
        /// <remarks/>
        a,
    }
    
    /// <remarks/>
    public class searchDescriptionTable {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("td", typeof(searchDescriptionTableTRTD), IsNullable=false)]
        public searchDescriptionTableTRTD[][] tr;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class;
    }
    
    /// <remarks/>
    public class searchDescriptionDivTableTRTDNobrSpan {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string style;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    public class searchDescriptionDivTableTRTDNobr {
        
        /// <remarks/>
        public searchDescriptionDivTableTRTDNobrSpan span;
    }
    
    /// <remarks/>
    public class searchDescriptionDivTableTRTD {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nobr", typeof(searchDescriptionDivTableTRTDNobr))]
        [System.Xml.Serialization.XmlElementAttribute("br", typeof(object))]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string style;
    }
    
    /// <remarks/>
    public class searchDescriptionDivTableTR {
        
        /// <remarks/>
        public searchDescriptionDivTableTRTD td;
    }
    
    /// <remarks/>
    public class searchDescriptionDivTable {
        
        /// <remarks/>
        public searchDescriptionDivTableTR tr;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class;
    }
    
    /// <remarks/>
    public class searchDescriptionDiv {
        
        /// <remarks/>
        public object br;
        
        /// <remarks/>
        public searchDescriptionDivTable table;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string style;
    }
    
    /// <remarks/>
    public class searchDescription {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("b", typeof(searchDescriptionB))]
        [System.Xml.Serialization.XmlElementAttribute("a", typeof(searchDescriptionA))]
        [System.Xml.Serialization.XmlElementAttribute("div", typeof(searchDescriptionDiv))]
        [System.Xml.Serialization.XmlElementAttribute("i", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("table", typeof(searchDescriptionTable))]
        [System.Xml.Serialization.XmlElementAttribute("wbr", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("br", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        b,
        
        /// <remarks/>
        a,
        
        /// <remarks/>
        div,
        
        /// <remarks/>
        i,
        
        /// <remarks/>
        table,
        
        /// <remarks/>
        wbr,
        
        /// <remarks/>
        br,
    }
    
    /// <remarks/>
    public class searchCategory {
        
        /// <remarks/>
        public string category;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool nomenu;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nomenuSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        copyright,
        
        /// <remarks/>
        comment,
        
        /// <remarks/>
        created_by,
        
        /// <remarks/>
        version,
        
        /// <remarks/>
        email,
        
        /// <remarks/>
        link,
        
        /// <remarks/>
        description,
        
        /// <remarks/>
        COMMENT,
        
        /// <remarks/>
        todo,
        
        /// <remarks/>
        script,
        
        /// <remarks/>
        form,
        
        /// <remarks/>
        contributor,
        
        /// <remarks/>
        category,
        
        /// <remarks/>
        idea,
    }
}
